spring:
  application:
    name: api-user
  datasource:
    class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.40.191:3306/wtf?serverTimezone=Asia/Shanghai&&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  redis:
    host: 47.97.40.191
    port: 6379
    password:
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9010/eureka/

feign:
  hystrix:
    enabled: true #fallback可以展示

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wtf.user.mapper

jwt:
  config:
    key: wtf_key
    expirationTime: 3600000
