spring:
  application:
    name: api-article
  datasource:
    class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.40.191:3306/article?serverTimezone=Asia/Shanghai&&characterEncoding=utf-8
    username: root
    password: root
server:
  port: 9094
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9010/eureka/

feign:
  hystrix:
    enabled: true #fallback可以展示

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wtf.article.mapper

